-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 22:36:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reserva` DEFAULT CHARACTER SET utf8 ;
USE `reserva` ;

-- -----------------------------------------------------
-- Table `reserva`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`cliente` (
  `cedula_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(45) NULL,
  `telef_cliente` INT(10) NULL,
  `direc_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`cedula_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`mesa` (
  `id_mesa` INT NOT NULL,
  `cantidadperso_mesa` INT NULL,
  `ubicacion_mesa` VARCHAR(200) NULL,
  `precio_mesa` FLOAT NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`id_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`reserva` (
  `id_reserva` INT NOT NULL,
  `numperso_reserva` INT NULL,
  `fecha_reserva` DATE NULL,
  `Cliente_cedula_cliente` INT NOT NULL,
  `mesa_id_mesa` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `Cliente_cedula_cliente`, `mesa_id_mesa`),
  INDEX `fk_reserva_Cliente_idx` (`Cliente_cedula_cliente` ASC),
  INDEX `fk_reserva_mesa1_idx` (`mesa_id_mesa` ASC),
  CONSTRAINT `fk_reserva_Cliente`
    FOREIGN KEY (`Cliente_cedula_cliente`)
    REFERENCES `reserva`.`cliente` (`cedula_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_mesa1`
    FOREIGN KEY (`mesa_id_mesa`)
    REFERENCES `reserva`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`menu` (
  `id_menu` INT NOT NULL,
  `nombre_menu` VARCHAR(100) NULL,
  `descripcion_menu` VARCHAR(200) NULL,
  `precio_menu` FLOAT NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`.`detallerecerva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva`.`detallerecerva` (
  `id_detalle` INT NOT NULL,
  `cantidad_detalle` INT NULL,
  `_id_menu` INT NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  `reserva_Cliente_cedula_cliente` INT NOT NULL,
  `reserva_mesa_id_mesa` INT NOT NULL,
  PRIMARY KEY (`id_detalle`, `_id_menu`, `reserva_id_reserva`, `reserva_Cliente_cedula_cliente`, `reserva_mesa_id_mesa`),
  INDEX `fk_detallerecerva_1_idx` (`_id_menu` ASC),
  INDEX `fk_detallerecerva_reserva1_idx` (`reserva_id_reserva` ASC, `reserva_Cliente_cedula_cliente` ASC, `reserva_mesa_id_mesa` ASC),
  CONSTRAINT `fk_detallerecerva_1`
    FOREIGN KEY (`_id_menu`)
    REFERENCES `reserva`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallerecerva_reserva1`
    FOREIGN KEY (`reserva_id_reserva` , `reserva_Cliente_cedula_cliente` , `reserva_mesa_id_mesa`)
    REFERENCES `reserva`.`reserva` (`id_reserva` , `Cliente_cedula_cliente` , `mesa_id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
